AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty
kiegroup/jbpm-wb pull request #1484
Opened 2021-03-12 11:06 UTC by akumar074

* Added tags to Display settings

**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-03-16 11:36 UTC, tomasdavidorg commented on jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java
> +        if(tags != null) {
```suggestion
        if (tags != null) {
```

2021-03-17 10:35 UTC, pefernan requested changes
@akumar074 would you add some testing please?

2021-04-14 08:11 UTC, tomasdavidorg approved these changes

2021-04-14 10:30 UTC, pefernan approved these changes
+1

2021-04-19 12:51 UTC, ederign approved these changes

2021-04-19 12:51 UTC, merged