JBPM-9945 Being able to park process execution on failed script task …
kiegroup/jbpm-wb pull request #1530
Opened 2021-11-12 15:11 UTC by bxf12315

…and re-execute it when resuming process flow

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/JBPM-9945](JBPM-9945)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/droolsjbpm-integration/pull/2651
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-11-12 15:12 UTC, bxf12315 commented
Jenkins run fdb

2021-11-13 07:47 UTC, nmirasch commented
@bxf12315 Is this change needed? regarding that ACTIVE_BORDER_COLOR is a configurable property at BC.

2021-11-13 10:29 UTC, bxf12315 commented
> @bxf12315 Is this change needed? regarding that ACTIVE_BORDER_COLOR is a configurable property at BC.

yes, now default ACTIVE_BORDER_COLOR is red, according to the issue and @lazarotti 's comment, we need to set it to blue, and set error node border to red.

2021-12-13 08:59 UTC, nmirasch commented
@bxf12315  I think we need to track this change of the active nodes color in another jira is unrelated to this one "Being able to park process execution on failed script task" and it has to be documented at release notes.

2021-12-13 09:07 UTC, nmirasch commented
@bxf12315  looking at this comment, I think it was the expected: https://issues.redhat.com/browse/BAPL-2159?focusedCommentId=19196629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19196629. And to me, to be consistent the new ERROR_BORDER_COLOR must be added as a configuration property as the others.

2021-12-13 09:44 UTC, bxf12315 commented
> @bxf12315 looking at this comment, I think it was the expected: https://issues.redhat.com/browse/BAPL-2159?focusedCommentId=19196629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19196629. And to me, to be consistent the new ERROR_BORDER_COLOR must be added as a configuration property as the others.

OK, @lazarotti  means, we need to create a new jira issue to add new configuration property, Could you please add a comment on the issue?

2021-12-16 00:37 UTC, bxf12315 commented
Jenkins run fdb

2021-12-20 10:21 UTC, bxf12315 commented
Jenkins run fdb

2021-12-21 16:02 UTC, nmirasch reviewed
Code looks good, I just added some minor formatting comments, feel free to review that.
About the commit message maybe something related with the error color configuration addition would reflect better what code does, regarding in the original jira has no reference to this color change introduction.

2022-01-03 09:21 UTC, jstastny-cz requested changes
There are some formatting issues.

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-common/jbpm-wb-common-api/src/main/java/org/jbpm/workbench/common/preferences/ManagePreferences.java
> +        defaultValue.processInstanceDiagramErrorNodeBorderColor = ERROR_BORDER_COLOR;
please move one line up, closer to the other similar fields initialization.

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-common/jbpm-wb-common-api/src/main/java/org/jbpm/workbench/common/preferences/ManagePreferences.java
> +    public String getProcessInstanceDiagramErrorNodeBorderColor() {
I would suggest moving these methods after `setProcessInstanceDiagramActiveNodeBorderColor` to keep similar methods next to each other.

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-api/src/main/java/org/jbpm/workbench/pr/service/ProcessRuntimeDataService.java
> +                                                                   String activeNodeBorderColor, String errorNodeBorderColor);
+1

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +        when(uiServicesClient.getProcessInstanceImageCustomColor("", null, "", "", "",""))
```suggestion
        when(uiServicesClient.getProcessInstanceImageCustomColor("", null, "", "", "", ""))
```

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                                                 "","")).thenReturn(SVG_WITH_LINK);
```suggestion
                                                                 "", "")).thenReturn(SVG_WITH_LINK);
```

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                                                 "","");
```suggestion
                                                                 "", "");
```

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                          completeNodeColor, completeNodeBorderColor, activeNodeBorderColor,"");
```suggestion
                                          completeNodeColor, completeNodeBorderColor, activeNodeBorderColor, "");
```

2022-01-03 09:21 UTC, jstastny-cz commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                                                    activeNodeBorderColor,"");
```suggestion
                                                                    activeNodeBorderColor, "");
```

2022-02-12 14:43 UTC, bxf12315 commented
Jenkins retest this

2022-02-12 14:43 UTC, bxf12315 commented
Jenkins run fdb

2022-02-14 08:28 UTC, bxf12315 commented
Jenkins retest this

2022-02-14 08:28 UTC, bxf12315 commented
Jenkins run fdb

2022-02-23 17:44 UTC, barboras7 commented
@bxf12315 could you please take a look at the rest of the formatting issues that Jan pointed out? I see two comments that are not marked as "Outdated". Once that is done, I'll check if everything is fixed in the UI and will QE approve the issue if it works as expected.

2022-02-24 07:24 UTC, bxf12315 commented
> @bxf12315 could you please take a look at the rest of the formatting issues that Jan pointed out? I see two comments that are not marked as "Outdated". Once that is done, I'll check if everything is fixed in the UI and will QE approve the issue if it works as expected.

Done

2022-02-24 07:24 UTC, bxf12315 commented
Jenkins run fdb

2022-02-24 17:25 UTC, nmirasch commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                          completeNodeColor, completeNodeBorderColor, activeNodeBorderColor, "");
@bxf12315 makes sense that testProcessInstanceImageCustomColors checks specific values for color configuration. Could you add a variable with  an specific error Node Color and check that value is used i the call. (Like it is done for the other colors)

2022-02-25 07:02 UTC, bxf12315 commented
Jenkins run fdb

2022-02-25 11:11 UTC, nmirasch commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                          completeNodeColor, completeNodeBorderColor, activeNodeBorderColor, "");
@bxf12315  that's it, thanks!

2022-02-25 15:41 UTC, nmirasch commented
@bxf12315 There are two missed constants related with the new configuration parameter..

![image](https://user-images.githubusercontent.com/2443754/155743409-8b1eca74-7610-45f6-9bb9-35e31609ed41.png)

the Constants for the new parameter have to be added like the other ones here:
https://github.com/kiegroup/jbpm-wb/blob/75bc89830bb741fed00a09a75d8087d8e74e1c89/jbpm-wb-common/jbpm-wb-common-client/src/main/resources/org/jbpm/workbench/common/client/resources/i18n/Constants.properties#L80

2022-02-25 16:22 UTC, bxf12315 commented
> @bxf12315 There are two missed constants related with the new configuration parameter..
> 
> ![image](https://user-images.githubusercontent.com/2443754/155743409-8b1eca74-7610-45f6-9bb9-35e31609ed41.png)
> 
> the Constants for the new parameter have to be added like the other ones here:
> 
> https://github.com/kiegroup/jbpm-wb/blob/75bc89830bb741fed00a09a75d8087d8e74e1c89/jbpm-wb-common/jbpm-wb-common-client/src/main/resources/org/jbpm/workbench/common/client/resources/i18n/Constants.properties#L80

updated

2022-02-25 16:22 UTC, bxf12315 commented
Jenkins run fdb

2022-02-27 13:46 UTC, bxf12315 commented
Jenkins run fdb

2022-02-28 08:26 UTC, jstastny-cz reviewed
My previous concerns were resolved. For overall final approval please consider @barboras7 reviews, I won't be available.

2022-02-28 08:35 UTC, nmirasch commented
Jenkins run fdb

2022-03-01 09:25 UTC, nmirasch approved these changes

2022-03-07 06:43 UTC, barboras7 commented
@bxf12315 Could you please provide more information on how to reproduce the issue? I successfully reproduced that the active node color is blue by default. However, I am not able to find a way to cause an error node. Could you please help? I talked with Neus as well, none of us is able to produce an error node.

2022-03-07 12:53 UTC, barboras7 commented
Hi @bxf12315,
does a custom color for error node work for you? I tried to change both active node color and error node color and only the active node color setting was reflected in the diagram, see attached screenshots. 
![Screenshot from 2022-03-07 13-48-27](https://user-images.githubusercontent.com/11525583/157038234-b89325ed-16d7-4266-8c2b-af034df9887b.png)
![Screenshot from 2022-03-07 13-05-30](https://user-images.githubusercontent.com/11525583/157038237-06cde45d-0d99-4486-82fd-ad727954aa81.png)
![Screenshot from 2022-03-07 13-05-05](https://user-images.githubusercontent.com/11525583/157038239-74fa7483-3267-442c-a8b8-169dfb394212.png)

2022-03-08 07:24 UTC, nmirasch commented
Jenkins run fdb

2022-03-09 14:09 UTC, barboras7 commented
Hi @bxf12315,
could you please check the functionality for setting custom color of a failed async node? This is still not working for me. I can set a custom color for an active node, but not for failed async node. 

Also, please, take a look at the UI messages provided in the Admin page. We agreed that the issue is not "error node" but "failed async node" and this should be also reflected in what the user sees. 
![Screenshot from 2022-03-09 15-03-21](https://user-images.githubusercontent.com/11525583/157458002-cb6e7210-473c-4af8-b6a9-0bf5a7db88f3.png)

2022-03-09 15:35 UTC, bxf12315 commented
> Hi @bxf12315, could you please check the functionality for setting custom color of a failed async node? This is still not working for me. I can set a custom color for an active node, but not for failed async node.
> 
> Also, please, take a look at the UI messages provided in the Admin page. We agreed that the issue is not "error node" but "failed async node" and this should be also reflected in what the user sees. ![Screenshot from 2022-03-09 15-03-21](https://user-images.githubusercontent.com/11525583/157458002-cb6e7210-473c-4af8-b6a9-0bf5a7db88f3.png)

ok working on it.

2022-03-10 05:34 UTC, bxf12315 commented
> Hi @bxf12315, could you please check the functionality for setting custom color of a failed async node? This is still not working for me. I can set a custom color for an active node, but not for failed async node.
> 
> Also, please, take a look at the UI messages provided in the Admin page. We agreed that the issue is not "error node" but "failed async node" and this should be also reflected in what the user sees. ![Screenshot from 2022-03-09 15-03-21](https://user-images.githubusercontent.com/11525583/157458002-cb6e7210-473c-4af8-b6a9-0bf5a7db88f3.png)

updated, please check it.

2022-03-10 05:34 UTC, bxf12315 commented
Jenkins run fdb

2022-03-10 05:36 UTC, bxf12315 commented
Jenkins run fdb

2022-03-10 12:54 UTC, barboras7 requested changes

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-common/jbpm-wb-common-client/src/main/resources/org/jbpm/workbench/common/client/resources/i18n/Constants.properties
> +ManagePreferences.ProcessInstanceDiagramErrorNodeBorderColor=Process instance diagram failed async node border color
```suggestion
ManagePreferences.ProcessInstanceDiagramFailedAsyncNodeBorderColor=Process instance diagram failed async node border color
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-common/jbpm-wb-common-client/src/main/resources/org/jbpm/workbench/common/client/resources/i18n/Constants.properties
> +ManagePreferences.ProcessInstanceDiagramErrorNodeBorderColor.Help=Set the color of failed async nodes border at process instance diagram.
```suggestion
ManagePreferences.ProcessInstanceDiagramFailedAsyncNodeBorderColor.Help=Set the color of failed async nodes border at process instance diagram.
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-api/src/main/java/org/jbpm/workbench/pr/service/ProcessImageService.java
> +                                     String errorNodeBorderColor);
```suggestion
                                     String failedAsyncNodeBorderColor);
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-api/src/main/java/org/jbpm/workbench/pr/service/ProcessRuntimeDataService.java
> +                                                                   String errorNodeBorderColor);
```suggestion
                                                                   String failedAsyncNodeBorderColor);
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImpl.java
> +                                            String errorNodeBorderColor) {
```suggestion
                                            String failedAsyncNodeBorderColor) {
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImpl.java
> +                                                                                            errorNodeBorderColor));
```suggestion
                                                                                            failedAsyncNodeBorderColor));
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessRuntimeDataServiceImpl.java
> +                                                                          String completedNodeBorderColor, String activeNodeBorderColor, String errorNodeBorderColor) {
```suggestion
                                                                          String completedNodeBorderColor, String activeNodeBorderColor, String failedAsyncNodeBorderColor) {
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessRuntimeDataServiceImpl.java
> +                                                                            errorNodeBorderColor));
```suggestion
                                                                            failedAsyncNodeBorderColor));
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +        String errorNodeBorderColor = "#FF0000";
```suggestion
        String failedAsyncNodeBorderColor = "#FF0000";
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                          completeNodeColor, completeNodeBorderColor, activeNodeBorderColor, errorNodeBorderColor);
```suggestion
                                          completeNodeColor, completeNodeBorderColor, activeNodeBorderColor, failedAsyncNodeBorderColor);
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessImageServiceImplTest.java
> +                                                                    activeNodeBorderColor, errorNodeBorderColor);
```suggestion
                                                                    activeNodeBorderColor, failedAsyncNodeBorderColor);
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramPresenter.java
> +                                            preferences.getProcessInstanceDiagramErrorNodeBorderColor());
```suggestion
                                            preferences.getProcessInstanceDiagramFailedAsyncNodeBorderColor());
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramPresenterTest.java
> +    private String errorNodeBorderColor = "#888885";
```suggestion
    private String failedAsyncNodeBorderColor = "#888885";
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramPresenterTest.java
> +        when(preferences.getProcessInstanceDiagramErrorNodeBorderColor()).thenReturn(errorNodeBorderColor);
```suggestion
        when(preferences.getProcessInstanceDiagramFailedAsyncNodeBorderColor()).thenReturn(failedAsyncNodeBorderColor);
```

2022-03-10 12:54 UTC, barboras7 commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramPresenterTest.java
> +        verify(processService).getProcessInstanceDiagramSummary(processInstance.getProcessInstanceKey(), completeNodeColor, completeNodeBorderColor, activeNodeBorderColor, errorNodeBorderColor);
```suggestion
        verify(processService).getProcessInstanceDiagramSummary(processInstance.getProcessInstanceKey(), completeNodeColor, completeNodeBorderColor, activeNodeBorderColor, failedAsyncNodeBorderColor);
```

2022-03-11 16:03 UTC, bxf12315 commented
Jenkins run fdb

2022-03-15 08:20 UTC, nmirasch requested changes
@bxf12315 I just left a minor comment about  the renaming of a constant. Overall it  looks good to me and it works fine.

2022-03-15 08:28 UTC, nmirasch commented
@bxf12315   could you rename the commit to "JBPM-9979: Mark async active nodes and change default active node border color" to reflect what it is really adding/changing?

2022-03-15 09:45 UTC, barboras7 requested changes

2022-03-15 09:45 UTC, barboras7 commented on jbpm-wb-common/jbpm-wb-common-api/src/main/java/org/jbpm/workbench/common/preferences/ManagePreferences.java
> +        defaultValue.processInstanceDiagramActiveAsyncNodeBorderColor = ERROR_BORDER_COLOR;
```suggestion
        defaultValue.processInstanceDiagramActiveAsyncNodeBorderColor = ACTIVE_ASYNC_BORDER_COLOR;
```

2022-03-15 11:34 UTC, nmirasch commented
@bxf12315 the commit message is what needs to be renamed, just to track the feature once it's merged

2022-03-15 11:44 UTC, bxf12315 commented
> @bxf12315 the commit message is what needs to be renamed, just to track the feature once it's merged

Done

2022-03-15 15:51 UTC, nmirasch commented
Jenkins run fdb

2022-03-16 08:56 UTC, nmirasch approved these changes

2022-03-16 10:01 UTC, barboras7 approved these changes

2022-03-18 10:04 UTC, merged