[JBPM-10218] Add italian translation
kiegroup/jbpm-wb pull request #1604
Opened 2024-01-13 09:45 UTC by gjed

Add support for italian translation

**JIRA**: [JBPM-10218](https://issues.redhat.com/browse/JBPM-10218)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2024-01-16 14:03 UTC, gjed commented
Rebased gjed/i18n_it on main branch

2024-02-21 11:47 UTC, mareknovotny commented
ok to test

2024-07-25 15:29 UTC, pibizza requested changes
I have added a number of suggestions. Most of them are rather trivial to make the italian sound a bit more natural.

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Process_Id=Id Processo
```suggestion
Process_Id=Id del Processo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Process_Instance_Id=Id Istanza Processo
```suggestion
Process_Instance_Id=Id dell''Istanza di Processo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Process_Instance_Details=Dettagli Istanza Processo
```suggestion
Process_Instance_Details=Dettagli dell'Istanza di Processo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Process_Instance_Correlation_Key=Chiave di Correlazione Istanza Processo
```suggestion
Process_Instance_Correlation_Key=Chiave di Correlazione dell''Istanza di Processo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Task_Name=Nome Attività
```suggestion
Task_Name=Nome dell''Attività
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Process_Context=Contesto Processo
```suggestion
Process_Context=Contesto del Processo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Suspend_tasks=Sospendi attività selezionate
```suggestion
Suspend_tasks=Sospendi le attività selezionate
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Release_tasks=Rilascia attività selezionate
```suggestion
Release_tasks=Rilascia le attività selezionate
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +DeploymentId=Id Deploy
```suggestion
DeploymentId=Id del Deploy
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Task_Form_Name=Nome Modulo Attività
```suggestion
Task_Form_Name=Nome del Modulo dell''Attività
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Task_Form=Modulo Attività
```suggestion
Task_Form=Modulo dell''Attività
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +ProcessSessionId=Id Sessione Processo
```suggestion
ProcessSessionId=Id della Sessione di Processo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants_it.properties
> +Task_Form=Modulo Attività
```suggestion
Task_Form=Modulo dell''Attività
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-integration/jbpm-wb-integration-client/src/main/resources/org/jbpm/workbench/wi/client/i18n/Constants_it.properties
> +Undeploy=Annulla Deploy
```suggestion
Undeploy=Annulla il Deploy
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-integration/jbpm-wb-integration-client/src/main/resources/org/jbpm/workbench/wi/client/i18n/Constants_it.properties
> +GroupID=ID Gruppo
```suggestion
GroupID=ID del Gruppo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-integration/jbpm-wb-integration-client/src/main/resources/org/jbpm/workbench/wi/client/i18n/Constants_it.properties
> +PersistenceUnit=Nome Persistence unit
```suggestion
PersistenceUnit=Nome dell'Unità di Persistenza
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-integration/jbpm-wb-integration-client/src/main/resources/org/jbpm/workbench/wi/client/i18n/Constants_it.properties
> +AuditPersistenceUnit=Nome Persistence unit di Audit
```suggestion
AuditPersistenceUnit=Nome dell'Unità di Persistenza di Audit
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-integration/jbpm-wb-integration-client/src/main/resources/org/jbpm/workbench/wi/client/i18n/Constants_it.properties
> +EnterValue=Inserisci valore
```suggestion
EnterValue=Inserisci il valore
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-integration/jbpm-wb-integration-client/src/main/resources/org/jbpm/workbench/wi/client/i18n/Constants_it.properties
> +CanNotRemoveServiceTaskMessage=Impossibile rimuovere l''attività personalizzata {0}, in quanto è utilizzata da almeno un progetto. Rimuoverla da tutti i progetti prima.
```suggestion
CanNotRemoveServiceTaskMessage=Impossibile rimuovere l''attività personalizzata {0}, in quanto è utilizzata da almeno un progetto. Rimuoverla  prima da tutti i progetti.
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Variables_Name=Nome variabile
```suggestion
Variables_Name=Nome della variabile
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Variable_Value=Valore variabile
```suggestion
Variable_Value=Valore della variabile
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +View_Process_Instances=Visualizza istanze di processo
```suggestion
View_Process_Instances=Visualizza le istanze di processo
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Process_Definition_Id=ID definizione
```suggestion
Process_Definition_Id=ID della definizione
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Process_Definition_Name=Nome definizione
```suggestion
Process_Definition_Name=Nome della definizione
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Process_Definition_Version=Versione definizione
```suggestion
Process_Definition_Version=Versione della definizione
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Process_Instance_Details=Dettagli istanza
```suggestion
Process_Instance_Details=Dettagli dell'istanza
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Process_Instance_State=Stato istanza
```suggestion
Process_Instance_State=Stato dell''istanza
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +ViewTasks=Visualizza attività
```suggestion
ViewTasks=Visualizza le attività
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +ViewJobs=Visualizza lavori
```suggestion
ViewJobs=Visualizza i lavori
```

2024-07-25 15:29 UTC, pibizza commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Parent_Process_Instance_Id=ID istanza del processo padre
```suggestion
Parent_Process_Instance_Id=ID dell'istanza del processo padre
```

2024-07-26 14:37 UTC, mareknovotny commented
it seems that i took suggestions wrongly as some had not escaped form or quotes :(

2024-07-26 14:43 UTC, mareknovotny commented on jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants_it.properties
> +Parent_Process_Instance_Id=ID dell'istanza del processo padre
```suggestion
Parent_Process_Instance_Id=ID dell''istanza del processo padre
```

2024-07-26 14:44 UTC, pibizza approved these changes

2024-07-26 14:51 UTC, mareknovotny commented on jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/Constants_it.properties
> +CaseStarted=Caso con id {0} avviato!
Isn't this better to keep id there? @pibizza ?

2024-07-26 14:51 UTC, mareknovotny commented on jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/Constants_it.properties
> +ProcessStarted=Processo Id: {0} avviato!
Isn't this better to keep id there? @pibizza ?

2024-07-26 15:07 UTC, pibizza commented on jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/Constants_it.properties
> +ProcessStarted=Processo Id: {0} avviato!
We can keep it.

2024-07-26 15:07 UTC, pibizza commented on jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/Constants_it.properties
> +CaseStarted=Caso con id {0} avviato!
We can keep it

2024-07-29 07:42 UTC, mareknovotny commented on jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/Constants_it.properties
> +ProcessStarted=Processo Id: {0} avviato!
ok

2024-09-17 08:02 UTC, merged