RHPAM-4889: using a feature flag to enable/disable strict mode.
kiegroup/jbpm-wb pull request #1606
Opened 2024-02-13 21:20 UTC by porcelli

Introducing a new environment variable `jbpm.wb.querymode` with possible values DEFAULT or STRICT.

If used Strict mode, the queries will be filtered.

By default it'll continue behave as before, without filtering the queries.

2024-02-14 05:52 UTC, martinweiler approved these changes
Nice solution @porcelli

2024-02-14 16:53 UTC, Rikkola approved these changes

2024-02-15 08:14 UTC, elguardian requested changes
I disagree with the solution. in my opinion is not a good solution as it is to restricted.
I would create a property like

"jbpm.wb.query.location" where you can specify where to find the query definitions.

we look first in the resources on the class loader and after in the file system (if not found). so it lets the control to the user.

2024-02-15 14:26 UTC, elguardian commented
unblocking this. but disagree with the solution as an URI will be more effective in the future.

2024-02-15 15:03 UTC, merged

2024-02-21 11:45 UTC, mareknovotny commented
guys you merged PR change with RED CI, i will revert it

```
[2024-02-15T14:48:00.641Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.10.0:check (default) on project jbpm-wb-kie-server-backend: You have 2 PMD violations. For more details see: /home/jenkins/workspace/KIE/main/pullrequest/jbpm-wb-main.pr/bc/kiegroup_jbpm-wb/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/target/pmd.xml -> [Help 1]
[2024-02-15T14:48:00.641Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.10.0:check (default) on project jbpm-wb-kie-server-backend: You have 2 PMD violations. For more details see: /home/jenkins/workspace/KIE/main/pullrequest/jbpm-wb-main.pr/bc/kiegroup_jbpm-wb/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/target/pmd.xml
[2024-02-15T14:48:00.641Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2024-02-15T14:48:00.641Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2024-02-15T14:48:00.641Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2024-02-15T14:48:00.642Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2024-02-15T14:48:00.642Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2024-02-15T14:48:00.642Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2024-02-15T14:48:00.642Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2024-02-15T14:48:00.642Z] Caused by: org.apache.maven.plugin.MojoFailureException: You have 2 PMD violations. For more details see: /home/jenkins/workspace/KIE/main/pullrequest/jbpm-wb-main.pr/bc/kiegroup_jbpm-wb/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/target/pmd.xml
[2024-02-15T14:48:00.642Z]     at org.apache.maven.plugins.pmd.AbstractPmdViolationCheckMojo.executeCheck (AbstractPmdViolationCheckMojo.java:156)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.plugins.pmd.PmdViolationCheckMojo.execute (PmdViolationCheckMojo.java:82)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2024-02-15T14:48:00.642Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2024-02-15T14:48:00.642Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2024-02-15T14:48:00.642Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2024-02-15T14:48:00.642Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2024-02-15T14:48:00.642Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2024-02-15T14:48:00.642Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```